// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: call.proto

package com.ukelink.voip.proto;

public final class Call {
  private Call() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CallInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.voip.proto.CallInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
     */
    boolean hasFromUser();
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
     */
    Clientinfo.ClientInfo getFromUser();
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
     */
    Clientinfo.ClientInfoOrBuilder getFromUserOrBuilder();

    /**
     * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
     */
    boolean hasToUser();
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
     */
    Clientinfo.ClientInfo getToUser();
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
     */
    Clientinfo.ClientInfoOrBuilder getToUserOrBuilder();

    /**
     * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
     */
    int getCallMethodValue();
    /**
     * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
     */
    CallInfo.CallMethod getCallMethod();

    /**
     * <code>string originalId = 4;</code>
     */
    String getOriginalId();
    /**
     * <code>string originalId = 4;</code>
     */
    com.google.protobuf.ByteString
        getOriginalIdBytes();

    /**
     * <code>string indexId = 5;</code>
     */
    String getIndexId();
    /**
     * <code>string indexId = 5;</code>
     */
    com.google.protobuf.ByteString
        getIndexIdBytes();

    /**
     * <code>string callId = 6;</code>
     */
    String getCallId();
    /**
     * <code>string callId = 6;</code>
     */
    com.google.protobuf.ByteString
        getCallIdBytes();

    /**
     * <code>int64 messageTime = 7;</code>
     */
    long getMessageTime();

    /**
     * <code>bytes content = 8;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.ukelink.voip.proto.CallInfo}
   */
  public  static final class CallInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.voip.proto.CallInfo)
      CallInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CallInfo.newBuilder() to construct.
    private CallInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallInfo() {
      callMethod_ = 0;
      originalId_ = "";
      indexId_ = "";
      callId_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Clientinfo.ClientInfo.Builder subBuilder = null;
              if (fromUser_ != null) {
                subBuilder = fromUser_.toBuilder();
              }
              fromUser_ = input.readMessage(Clientinfo.ClientInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fromUser_);
                fromUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              Clientinfo.ClientInfo.Builder subBuilder = null;
              if (toUser_ != null) {
                subBuilder = toUser_.toBuilder();
              }
              toUser_ = input.readMessage(Clientinfo.ClientInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(toUser_);
                toUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              callMethod_ = rawValue;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              originalId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              indexId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              callId_ = s;
              break;
            }
            case 56: {

              messageTime_ = input.readInt64();
              break;
            }
            case 66: {

              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Call.internal_static_com_ukelink_voip_proto_CallInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Call.internal_static_com_ukelink_voip_proto_CallInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallInfo.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.ukelink.voip.proto.CallInfo.CallMethod}
     */
    public enum CallMethod
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MESSAGE_STATE_NONE = 0;</code>
       */
      MESSAGE_STATE_NONE(0),
      /**
       * <code>MESSAGE_STATE_CREATE = 1;</code>
       */
      MESSAGE_STATE_CREATE(1),
      /**
       * <code>MESSAGE_STATE_ANSWER = 2;</code>
       */
      MESSAGE_STATE_ANSWER(2),
      /**
       * <code>MESSAGE_STATE_HUANGUP = 3;</code>
       */
      MESSAGE_STATE_HUANGUP(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MESSAGE_STATE_NONE = 0;</code>
       */
      public static final int MESSAGE_STATE_NONE_VALUE = 0;
      /**
       * <code>MESSAGE_STATE_CREATE = 1;</code>
       */
      public static final int MESSAGE_STATE_CREATE_VALUE = 1;
      /**
       * <code>MESSAGE_STATE_ANSWER = 2;</code>
       */
      public static final int MESSAGE_STATE_ANSWER_VALUE = 2;
      /**
       * <code>MESSAGE_STATE_HUANGUP = 3;</code>
       */
      public static final int MESSAGE_STATE_HUANGUP_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static CallMethod valueOf(int value) {
        return forNumber(value);
      }

      public static CallMethod forNumber(int value) {
        switch (value) {
          case 0: return MESSAGE_STATE_NONE;
          case 1: return MESSAGE_STATE_CREATE;
          case 2: return MESSAGE_STATE_ANSWER;
          case 3: return MESSAGE_STATE_HUANGUP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CallMethod>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CallMethod> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CallMethod>() {
              public CallMethod findValueByNumber(int number) {
                return CallMethod.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return CallInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final CallMethod[] VALUES = values();

      public static CallMethod valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CallMethod(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.ukelink.voip.proto.CallInfo.CallMethod)
    }

    public static final int FROMUSER_FIELD_NUMBER = 1;
    private Clientinfo.ClientInfo fromUser_;
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
     */
    public boolean hasFromUser() {
      return fromUser_ != null;
    }
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
     */
    public Clientinfo.ClientInfo getFromUser() {
      return fromUser_ == null ? Clientinfo.ClientInfo.getDefaultInstance() : fromUser_;
    }
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
     */
    public Clientinfo.ClientInfoOrBuilder getFromUserOrBuilder() {
      return getFromUser();
    }

    public static final int TOUSER_FIELD_NUMBER = 2;
    private Clientinfo.ClientInfo toUser_;
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
     */
    public boolean hasToUser() {
      return toUser_ != null;
    }
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
     */
    public Clientinfo.ClientInfo getToUser() {
      return toUser_ == null ? Clientinfo.ClientInfo.getDefaultInstance() : toUser_;
    }
    /**
     * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
     */
    public Clientinfo.ClientInfoOrBuilder getToUserOrBuilder() {
      return getToUser();
    }

    public static final int CALLMETHOD_FIELD_NUMBER = 3;
    private int callMethod_;
    /**
     * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
     */
    public int getCallMethodValue() {
      return callMethod_;
    }
    /**
     * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
     */
    public CallMethod getCallMethod() {
      @SuppressWarnings("deprecation")
      CallMethod result = CallMethod.valueOf(callMethod_);
      return result == null ? CallMethod.UNRECOGNIZED : result;
    }

    public static final int ORIGINALID_FIELD_NUMBER = 4;
    private volatile Object originalId_;
    /**
     * <code>string originalId = 4;</code>
     */
    public String getOriginalId() {
      Object ref = originalId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        originalId_ = s;
        return s;
      }
    }
    /**
     * <code>string originalId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOriginalIdBytes() {
      Object ref = originalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        originalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEXID_FIELD_NUMBER = 5;
    private volatile Object indexId_;
    /**
     * <code>string indexId = 5;</code>
     */
    public String getIndexId() {
      Object ref = indexId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        indexId_ = s;
        return s;
      }
    }
    /**
     * <code>string indexId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIndexIdBytes() {
      Object ref = indexId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        indexId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CALLID_FIELD_NUMBER = 6;
    private volatile Object callId_;
    /**
     * <code>string callId = 6;</code>
     */
    public String getCallId() {
      Object ref = callId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        callId_ = s;
        return s;
      }
    }
    /**
     * <code>string callId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCallIdBytes() {
      Object ref = callId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        callId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETIME_FIELD_NUMBER = 7;
    private long messageTime_;
    /**
     * <code>int64 messageTime = 7;</code>
     */
    public long getMessageTime() {
      return messageTime_;
    }

    public static final int CONTENT_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 8;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fromUser_ != null) {
        output.writeMessage(1, getFromUser());
      }
      if (toUser_ != null) {
        output.writeMessage(2, getToUser());
      }
      if (callMethod_ != CallMethod.MESSAGE_STATE_NONE.getNumber()) {
        output.writeEnum(3, callMethod_);
      }
      if (!getOriginalIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, originalId_);
      }
      if (!getIndexIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, indexId_);
      }
      if (!getCallIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, callId_);
      }
      if (messageTime_ != 0L) {
        output.writeInt64(7, messageTime_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(8, content_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fromUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFromUser());
      }
      if (toUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getToUser());
      }
      if (callMethod_ != CallMethod.MESSAGE_STATE_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, callMethod_);
      }
      if (!getOriginalIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, originalId_);
      }
      if (!getIndexIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, indexId_);
      }
      if (!getCallIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, callId_);
      }
      if (messageTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, messageTime_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CallInfo)) {
        return super.equals(obj);
      }
      CallInfo other = (CallInfo) obj;

      if (hasFromUser() != other.hasFromUser()) return false;
      if (hasFromUser()) {
        if (!getFromUser()
            .equals(other.getFromUser())) return false;
      }
      if (hasToUser() != other.hasToUser()) return false;
      if (hasToUser()) {
        if (!getToUser()
            .equals(other.getToUser())) return false;
      }
      if (callMethod_ != other.callMethod_) return false;
      if (!getOriginalId()
          .equals(other.getOriginalId())) return false;
      if (!getIndexId()
          .equals(other.getIndexId())) return false;
      if (!getCallId()
          .equals(other.getCallId())) return false;
      if (getMessageTime()
          != other.getMessageTime()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFromUser()) {
        hash = (37 * hash) + FROMUSER_FIELD_NUMBER;
        hash = (53 * hash) + getFromUser().hashCode();
      }
      if (hasToUser()) {
        hash = (37 * hash) + TOUSER_FIELD_NUMBER;
        hash = (53 * hash) + getToUser().hashCode();
      }
      hash = (37 * hash) + CALLMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + callMethod_;
      hash = (37 * hash) + ORIGINALID_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalId().hashCode();
      hash = (37 * hash) + INDEXID_FIELD_NUMBER;
      hash = (53 * hash) + getIndexId().hashCode();
      hash = (37 * hash) + CALLID_FIELD_NUMBER;
      hash = (53 * hash) + getCallId().hashCode();
      hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageTime());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CallInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CallInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CallInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.voip.proto.CallInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.voip.proto.CallInfo)
        CallInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Call.internal_static_com_ukelink_voip_proto_CallInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Call.internal_static_com_ukelink_voip_proto_CallInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CallInfo.class, Builder.class);
      }

      // Construct using com.ukelink.voip.proto.Call.CallInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (fromUserBuilder_ == null) {
          fromUser_ = null;
        } else {
          fromUser_ = null;
          fromUserBuilder_ = null;
        }
        if (toUserBuilder_ == null) {
          toUser_ = null;
        } else {
          toUser_ = null;
          toUserBuilder_ = null;
        }
        callMethod_ = 0;

        originalId_ = "";

        indexId_ = "";

        callId_ = "";

        messageTime_ = 0L;

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Call.internal_static_com_ukelink_voip_proto_CallInfo_descriptor;
      }

      @Override
      public CallInfo getDefaultInstanceForType() {
        return CallInfo.getDefaultInstance();
      }

      @Override
      public CallInfo build() {
        CallInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CallInfo buildPartial() {
        CallInfo result = new CallInfo(this);
        if (fromUserBuilder_ == null) {
          result.fromUser_ = fromUser_;
        } else {
          result.fromUser_ = fromUserBuilder_.build();
        }
        if (toUserBuilder_ == null) {
          result.toUser_ = toUser_;
        } else {
          result.toUser_ = toUserBuilder_.build();
        }
        result.callMethod_ = callMethod_;
        result.originalId_ = originalId_;
        result.indexId_ = indexId_;
        result.callId_ = callId_;
        result.messageTime_ = messageTime_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CallInfo) {
          return mergeFrom((CallInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CallInfo other) {
        if (other == CallInfo.getDefaultInstance()) return this;
        if (other.hasFromUser()) {
          mergeFromUser(other.getFromUser());
        }
        if (other.hasToUser()) {
          mergeToUser(other.getToUser());
        }
        if (other.callMethod_ != 0) {
          setCallMethodValue(other.getCallMethodValue());
        }
        if (!other.getOriginalId().isEmpty()) {
          originalId_ = other.originalId_;
          onChanged();
        }
        if (!other.getIndexId().isEmpty()) {
          indexId_ = other.indexId_;
          onChanged();
        }
        if (!other.getCallId().isEmpty()) {
          callId_ = other.callId_;
          onChanged();
        }
        if (other.getMessageTime() != 0L) {
          setMessageTime(other.getMessageTime());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CallInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CallInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Clientinfo.ClientInfo fromUser_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Clientinfo.ClientInfo, Clientinfo.ClientInfo.Builder, Clientinfo.ClientInfoOrBuilder> fromUserBuilder_;
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      public boolean hasFromUser() {
        return fromUserBuilder_ != null || fromUser_ != null;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      public Clientinfo.ClientInfo getFromUser() {
        if (fromUserBuilder_ == null) {
          return fromUser_ == null ? Clientinfo.ClientInfo.getDefaultInstance() : fromUser_;
        } else {
          return fromUserBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      public Builder setFromUser(Clientinfo.ClientInfo value) {
        if (fromUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fromUser_ = value;
          onChanged();
        } else {
          fromUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      public Builder setFromUser(
          Clientinfo.ClientInfo.Builder builderForValue) {
        if (fromUserBuilder_ == null) {
          fromUser_ = builderForValue.build();
          onChanged();
        } else {
          fromUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      public Builder mergeFromUser(Clientinfo.ClientInfo value) {
        if (fromUserBuilder_ == null) {
          if (fromUser_ != null) {
            fromUser_ =
              Clientinfo.ClientInfo.newBuilder(fromUser_).mergeFrom(value).buildPartial();
          } else {
            fromUser_ = value;
          }
          onChanged();
        } else {
          fromUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      public Builder clearFromUser() {
        if (fromUserBuilder_ == null) {
          fromUser_ = null;
          onChanged();
        } else {
          fromUser_ = null;
          fromUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      public Clientinfo.ClientInfo.Builder getFromUserBuilder() {
        
        onChanged();
        return getFromUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      public Clientinfo.ClientInfoOrBuilder getFromUserOrBuilder() {
        if (fromUserBuilder_ != null) {
          return fromUserBuilder_.getMessageOrBuilder();
        } else {
          return fromUser_ == null ?
              Clientinfo.ClientInfo.getDefaultInstance() : fromUser_;
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo fromUser = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Clientinfo.ClientInfo, Clientinfo.ClientInfo.Builder, Clientinfo.ClientInfoOrBuilder>
          getFromUserFieldBuilder() {
        if (fromUserBuilder_ == null) {
          fromUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Clientinfo.ClientInfo, Clientinfo.ClientInfo.Builder, Clientinfo.ClientInfoOrBuilder>(
                  getFromUser(),
                  getParentForChildren(),
                  isClean());
          fromUser_ = null;
        }
        return fromUserBuilder_;
      }

      private Clientinfo.ClientInfo toUser_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Clientinfo.ClientInfo, Clientinfo.ClientInfo.Builder, Clientinfo.ClientInfoOrBuilder> toUserBuilder_;
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      public boolean hasToUser() {
        return toUserBuilder_ != null || toUser_ != null;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      public Clientinfo.ClientInfo getToUser() {
        if (toUserBuilder_ == null) {
          return toUser_ == null ? Clientinfo.ClientInfo.getDefaultInstance() : toUser_;
        } else {
          return toUserBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      public Builder setToUser(Clientinfo.ClientInfo value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          toUser_ = value;
          onChanged();
        } else {
          toUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      public Builder setToUser(
          Clientinfo.ClientInfo.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          toUser_ = builderForValue.build();
          onChanged();
        } else {
          toUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      public Builder mergeToUser(Clientinfo.ClientInfo value) {
        if (toUserBuilder_ == null) {
          if (toUser_ != null) {
            toUser_ =
              Clientinfo.ClientInfo.newBuilder(toUser_).mergeFrom(value).buildPartial();
          } else {
            toUser_ = value;
          }
          onChanged();
        } else {
          toUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      public Builder clearToUser() {
        if (toUserBuilder_ == null) {
          toUser_ = null;
          onChanged();
        } else {
          toUser_ = null;
          toUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      public Clientinfo.ClientInfo.Builder getToUserBuilder() {
        
        onChanged();
        return getToUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      public Clientinfo.ClientInfoOrBuilder getToUserOrBuilder() {
        if (toUserBuilder_ != null) {
          return toUserBuilder_.getMessageOrBuilder();
        } else {
          return toUser_ == null ?
              Clientinfo.ClientInfo.getDefaultInstance() : toUser_;
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.ClientInfo toUser = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Clientinfo.ClientInfo, Clientinfo.ClientInfo.Builder, Clientinfo.ClientInfoOrBuilder>
          getToUserFieldBuilder() {
        if (toUserBuilder_ == null) {
          toUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Clientinfo.ClientInfo, Clientinfo.ClientInfo.Builder, Clientinfo.ClientInfoOrBuilder>(
                  getToUser(),
                  getParentForChildren(),
                  isClean());
          toUser_ = null;
        }
        return toUserBuilder_;
      }

      private int callMethod_ = 0;
      /**
       * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
       */
      public int getCallMethodValue() {
        return callMethod_;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
       */
      public Builder setCallMethodValue(int value) {
        callMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
       */
      public CallMethod getCallMethod() {
        @SuppressWarnings("deprecation")
        CallMethod result = CallMethod.valueOf(callMethod_);
        return result == null ? CallMethod.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
       */
      public Builder setCallMethod(CallMethod value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        callMethod_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo.CallMethod callMethod = 3;</code>
       */
      public Builder clearCallMethod() {
        
        callMethod_ = 0;
        onChanged();
        return this;
      }

      private Object originalId_ = "";
      /**
       * <code>string originalId = 4;</code>
       */
      public String getOriginalId() {
        Object ref = originalId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          originalId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string originalId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOriginalIdBytes() {
        Object ref = originalId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          originalId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string originalId = 4;</code>
       */
      public Builder setOriginalId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        originalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string originalId = 4;</code>
       */
      public Builder clearOriginalId() {
        
        originalId_ = getDefaultInstance().getOriginalId();
        onChanged();
        return this;
      }
      /**
       * <code>string originalId = 4;</code>
       */
      public Builder setOriginalIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        originalId_ = value;
        onChanged();
        return this;
      }

      private Object indexId_ = "";
      /**
       * <code>string indexId = 5;</code>
       */
      public String getIndexId() {
        Object ref = indexId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          indexId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string indexId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIndexIdBytes() {
        Object ref = indexId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          indexId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string indexId = 5;</code>
       */
      public Builder setIndexId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        indexId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string indexId = 5;</code>
       */
      public Builder clearIndexId() {
        
        indexId_ = getDefaultInstance().getIndexId();
        onChanged();
        return this;
      }
      /**
       * <code>string indexId = 5;</code>
       */
      public Builder setIndexIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        indexId_ = value;
        onChanged();
        return this;
      }

      private Object callId_ = "";
      /**
       * <code>string callId = 6;</code>
       */
      public String getCallId() {
        Object ref = callId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          callId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string callId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCallIdBytes() {
        Object ref = callId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          callId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string callId = 6;</code>
       */
      public Builder setCallId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        callId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string callId = 6;</code>
       */
      public Builder clearCallId() {
        
        callId_ = getDefaultInstance().getCallId();
        onChanged();
        return this;
      }
      /**
       * <code>string callId = 6;</code>
       */
      public Builder setCallIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        callId_ = value;
        onChanged();
        return this;
      }

      private long messageTime_ ;
      /**
       * <code>int64 messageTime = 7;</code>
       */
      public long getMessageTime() {
        return messageTime_;
      }
      /**
       * <code>int64 messageTime = 7;</code>
       */
      public Builder setMessageTime(long value) {
        
        messageTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageTime = 7;</code>
       */
      public Builder clearMessageTime() {
        
        messageTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 8;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 8;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 8;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.voip.proto.CallInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.voip.proto.CallInfo)
    private static final CallInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CallInfo();
    }

    public static CallInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CallInfo>
        PARSER = new com.google.protobuf.AbstractParser<CallInfo>() {
      @Override
      public CallInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CallInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CallInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public CallInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CallRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.voip.proto.CallRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
     */
    boolean hasCallInfo();
    /**
     * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
     */
    CallInfo getCallInfo();
    /**
     * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
     */
    CallInfoOrBuilder getCallInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.ukelink.voip.proto.CallRequest}
   */
  public  static final class CallRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.voip.proto.CallRequest)
      CallRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CallRequest.newBuilder() to construct.
    private CallRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallRequest() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              CallInfo.Builder subBuilder = null;
              if (callInfo_ != null) {
                subBuilder = callInfo_.toBuilder();
              }
              callInfo_ = input.readMessage(CallInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(callInfo_);
                callInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Call.internal_static_com_ukelink_voip_proto_CallRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Call.internal_static_com_ukelink_voip_proto_CallRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallRequest.class, Builder.class);
    }

    public static final int CALLINFO_FIELD_NUMBER = 1;
    private CallInfo callInfo_;
    /**
     * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
     */
    public boolean hasCallInfo() {
      return callInfo_ != null;
    }
    /**
     * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
     */
    public CallInfo getCallInfo() {
      return callInfo_ == null ? CallInfo.getDefaultInstance() : callInfo_;
    }
    /**
     * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
     */
    public CallInfoOrBuilder getCallInfoOrBuilder() {
      return getCallInfo();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (callInfo_ != null) {
        output.writeMessage(1, getCallInfo());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (callInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCallInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CallRequest)) {
        return super.equals(obj);
      }
      CallRequest other = (CallRequest) obj;

      if (hasCallInfo() != other.hasCallInfo()) return false;
      if (hasCallInfo()) {
        if (!getCallInfo()
            .equals(other.getCallInfo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCallInfo()) {
        hash = (37 * hash) + CALLINFO_FIELD_NUMBER;
        hash = (53 * hash) + getCallInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CallRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CallRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CallRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.voip.proto.CallRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.voip.proto.CallRequest)
        CallRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Call.internal_static_com_ukelink_voip_proto_CallRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Call.internal_static_com_ukelink_voip_proto_CallRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CallRequest.class, Builder.class);
      }

      // Construct using com.ukelink.voip.proto.Call.CallRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (callInfoBuilder_ == null) {
          callInfo_ = null;
        } else {
          callInfo_ = null;
          callInfoBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Call.internal_static_com_ukelink_voip_proto_CallRequest_descriptor;
      }

      @Override
      public CallRequest getDefaultInstanceForType() {
        return CallRequest.getDefaultInstance();
      }

      @Override
      public CallRequest build() {
        CallRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CallRequest buildPartial() {
        CallRequest result = new CallRequest(this);
        if (callInfoBuilder_ == null) {
          result.callInfo_ = callInfo_;
        } else {
          result.callInfo_ = callInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CallRequest) {
          return mergeFrom((CallRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CallRequest other) {
        if (other == CallRequest.getDefaultInstance()) return this;
        if (other.hasCallInfo()) {
          mergeCallInfo(other.getCallInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CallRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CallRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private CallInfo callInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CallInfo, CallInfo.Builder, CallInfoOrBuilder> callInfoBuilder_;
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      public boolean hasCallInfo() {
        return callInfoBuilder_ != null || callInfo_ != null;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      public CallInfo getCallInfo() {
        if (callInfoBuilder_ == null) {
          return callInfo_ == null ? CallInfo.getDefaultInstance() : callInfo_;
        } else {
          return callInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      public Builder setCallInfo(CallInfo value) {
        if (callInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          callInfo_ = value;
          onChanged();
        } else {
          callInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      public Builder setCallInfo(
          CallInfo.Builder builderForValue) {
        if (callInfoBuilder_ == null) {
          callInfo_ = builderForValue.build();
          onChanged();
        } else {
          callInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      public Builder mergeCallInfo(CallInfo value) {
        if (callInfoBuilder_ == null) {
          if (callInfo_ != null) {
            callInfo_ =
              CallInfo.newBuilder(callInfo_).mergeFrom(value).buildPartial();
          } else {
            callInfo_ = value;
          }
          onChanged();
        } else {
          callInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      public Builder clearCallInfo() {
        if (callInfoBuilder_ == null) {
          callInfo_ = null;
          onChanged();
        } else {
          callInfo_ = null;
          callInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      public CallInfo.Builder getCallInfoBuilder() {
        
        onChanged();
        return getCallInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      public CallInfoOrBuilder getCallInfoOrBuilder() {
        if (callInfoBuilder_ != null) {
          return callInfoBuilder_.getMessageOrBuilder();
        } else {
          return callInfo_ == null ?
              CallInfo.getDefaultInstance() : callInfo_;
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.CallInfo callInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CallInfo, CallInfo.Builder, CallInfoOrBuilder>
          getCallInfoFieldBuilder() {
        if (callInfoBuilder_ == null) {
          callInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CallInfo, CallInfo.Builder, CallInfoOrBuilder>(
                  getCallInfo(),
                  getParentForChildren(),
                  isClean());
          callInfo_ = null;
        }
        return callInfoBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.voip.proto.CallRequest)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.voip.proto.CallRequest)
    private static final CallRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CallRequest();
    }

    public static CallRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CallRequest>
        PARSER = new com.google.protobuf.AbstractParser<CallRequest>() {
      @Override
      public CallRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CallRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CallRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public CallRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CallResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.voip.proto.CallResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
     */
    boolean hasBaseResponse();
    /**
     * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
     */
    Baseresponse.BaseResponse getBaseResponse();
    /**
     * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
     */
    Baseresponse.BaseResponseOrBuilder getBaseResponseOrBuilder();

    /**
     * <code>string callId = 2;</code>
     */
    String getCallId();
    /**
     * <code>string callId = 2;</code>
     */
    com.google.protobuf.ByteString
        getCallIdBytes();
  }
  /**
   * Protobuf type {@code com.ukelink.voip.proto.CallResponse}
   */
  public  static final class CallResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.voip.proto.CallResponse)
      CallResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CallResponse.newBuilder() to construct.
    private CallResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallResponse() {
      callId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Baseresponse.BaseResponse.Builder subBuilder = null;
              if (baseResponse_ != null) {
                subBuilder = baseResponse_.toBuilder();
              }
              baseResponse_ = input.readMessage(Baseresponse.BaseResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResponse_);
                baseResponse_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              callId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Call.internal_static_com_ukelink_voip_proto_CallResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Call.internal_static_com_ukelink_voip_proto_CallResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallResponse.class, Builder.class);
    }

    public static final int BASERESPONSE_FIELD_NUMBER = 1;
    private Baseresponse.BaseResponse baseResponse_;
    /**
     * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
     */
    public boolean hasBaseResponse() {
      return baseResponse_ != null;
    }
    /**
     * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
     */
    public Baseresponse.BaseResponse getBaseResponse() {
      return baseResponse_ == null ? Baseresponse.BaseResponse.getDefaultInstance() : baseResponse_;
    }
    /**
     * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
     */
    public Baseresponse.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      return getBaseResponse();
    }

    public static final int CALLID_FIELD_NUMBER = 2;
    private volatile Object callId_;
    /**
     * <code>string callId = 2;</code>
     */
    public String getCallId() {
      Object ref = callId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        callId_ = s;
        return s;
      }
    }
    /**
     * <code>string callId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCallIdBytes() {
      Object ref = callId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        callId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseResponse_ != null) {
        output.writeMessage(1, getBaseResponse());
      }
      if (!getCallIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, callId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseResponse_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseResponse());
      }
      if (!getCallIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, callId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CallResponse)) {
        return super.equals(obj);
      }
      CallResponse other = (CallResponse) obj;

      if (hasBaseResponse() != other.hasBaseResponse()) return false;
      if (hasBaseResponse()) {
        if (!getBaseResponse()
            .equals(other.getBaseResponse())) return false;
      }
      if (!getCallId()
          .equals(other.getCallId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseResponse()) {
        hash = (37 * hash) + BASERESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getBaseResponse().hashCode();
      }
      hash = (37 * hash) + CALLID_FIELD_NUMBER;
      hash = (53 * hash) + getCallId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CallResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CallResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CallResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.voip.proto.CallResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.voip.proto.CallResponse)
        CallResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Call.internal_static_com_ukelink_voip_proto_CallResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Call.internal_static_com_ukelink_voip_proto_CallResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CallResponse.class, Builder.class);
      }

      // Construct using com.ukelink.voip.proto.Call.CallResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (baseResponseBuilder_ == null) {
          baseResponse_ = null;
        } else {
          baseResponse_ = null;
          baseResponseBuilder_ = null;
        }
        callId_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Call.internal_static_com_ukelink_voip_proto_CallResponse_descriptor;
      }

      @Override
      public CallResponse getDefaultInstanceForType() {
        return CallResponse.getDefaultInstance();
      }

      @Override
      public CallResponse build() {
        CallResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CallResponse buildPartial() {
        CallResponse result = new CallResponse(this);
        if (baseResponseBuilder_ == null) {
          result.baseResponse_ = baseResponse_;
        } else {
          result.baseResponse_ = baseResponseBuilder_.build();
        }
        result.callId_ = callId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CallResponse) {
          return mergeFrom((CallResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CallResponse other) {
        if (other == CallResponse.getDefaultInstance()) return this;
        if (other.hasBaseResponse()) {
          mergeBaseResponse(other.getBaseResponse());
        }
        if (!other.getCallId().isEmpty()) {
          callId_ = other.callId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CallResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CallResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Baseresponse.BaseResponse baseResponse_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Baseresponse.BaseResponse, Baseresponse.BaseResponse.Builder, Baseresponse.BaseResponseOrBuilder> baseResponseBuilder_;
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      public boolean hasBaseResponse() {
        return baseResponseBuilder_ != null || baseResponse_ != null;
      }
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      public Baseresponse.BaseResponse getBaseResponse() {
        if (baseResponseBuilder_ == null) {
          return baseResponse_ == null ? Baseresponse.BaseResponse.getDefaultInstance() : baseResponse_;
        } else {
          return baseResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      public Builder setBaseResponse(Baseresponse.BaseResponse value) {
        if (baseResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResponse_ = value;
          onChanged();
        } else {
          baseResponseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      public Builder setBaseResponse(
          Baseresponse.BaseResponse.Builder builderForValue) {
        if (baseResponseBuilder_ == null) {
          baseResponse_ = builderForValue.build();
          onChanged();
        } else {
          baseResponseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      public Builder mergeBaseResponse(Baseresponse.BaseResponse value) {
        if (baseResponseBuilder_ == null) {
          if (baseResponse_ != null) {
            baseResponse_ =
              Baseresponse.BaseResponse.newBuilder(baseResponse_).mergeFrom(value).buildPartial();
          } else {
            baseResponse_ = value;
          }
          onChanged();
        } else {
          baseResponseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      public Builder clearBaseResponse() {
        if (baseResponseBuilder_ == null) {
          baseResponse_ = null;
          onChanged();
        } else {
          baseResponse_ = null;
          baseResponseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      public Baseresponse.BaseResponse.Builder getBaseResponseBuilder() {
        
        onChanged();
        return getBaseResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      public Baseresponse.BaseResponseOrBuilder getBaseResponseOrBuilder() {
        if (baseResponseBuilder_ != null) {
          return baseResponseBuilder_.getMessageOrBuilder();
        } else {
          return baseResponse_ == null ?
              Baseresponse.BaseResponse.getDefaultInstance() : baseResponse_;
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.BaseResponse baseResponse = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Baseresponse.BaseResponse, Baseresponse.BaseResponse.Builder, Baseresponse.BaseResponseOrBuilder>
          getBaseResponseFieldBuilder() {
        if (baseResponseBuilder_ == null) {
          baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Baseresponse.BaseResponse, Baseresponse.BaseResponse.Builder, Baseresponse.BaseResponseOrBuilder>(
                  getBaseResponse(),
                  getParentForChildren(),
                  isClean());
          baseResponse_ = null;
        }
        return baseResponseBuilder_;
      }

      private Object callId_ = "";
      /**
       * <code>string callId = 2;</code>
       */
      public String getCallId() {
        Object ref = callId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          callId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string callId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCallIdBytes() {
        Object ref = callId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          callId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string callId = 2;</code>
       */
      public Builder setCallId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        callId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string callId = 2;</code>
       */
      public Builder clearCallId() {
        
        callId_ = getDefaultInstance().getCallId();
        onChanged();
        return this;
      }
      /**
       * <code>string callId = 2;</code>
       */
      public Builder setCallIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        callId_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.voip.proto.CallResponse)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.voip.proto.CallResponse)
    private static final CallResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CallResponse();
    }

    public static CallResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CallResponse>
        PARSER = new com.google.protobuf.AbstractParser<CallResponse>() {
      @Override
      public CallResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CallResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CallResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public CallResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_voip_proto_CallInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_voip_proto_CallInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_voip_proto_CallRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_voip_proto_CallRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_voip_proto_CallResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_voip_proto_CallResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ncall.proto\022\026com.ukelink.voip.proto\032\020cl" +
      "ientinfo.proto\032\022baseresponse.proto\"\205\003\n\010C" +
      "allInfo\0224\n\010fromUser\030\001 \001(\0132\".com.ukelink." +
      "voip.proto.ClientInfo\0222\n\006toUser\030\002 \001(\0132\"." +
      "com.ukelink.voip.proto.ClientInfo\022?\n\ncal" +
      "lMethod\030\003 \001(\0162+.com.ukelink.voip.proto.C" +
      "allInfo.CallMethod\022\022\n\noriginalId\030\004 \001(\t\022\017" +
      "\n\007indexId\030\005 \001(\t\022\016\n\006callId\030\006 \001(\t\022\023\n\013messa" +
      "geTime\030\007 \001(\003\022\017\n\007content\030\010 \001(\014\"s\n\nCallMet" +
      "hod\022\026\n\022MESSAGE_STATE_NONE\020\000\022\030\n\024MESSAGE_S" +
      "TATE_CREATE\020\001\022\030\n\024MESSAGE_STATE_ANSWER\020\002\022" +
      "\031\n\025MESSAGE_STATE_HUANGUP\020\003\"A\n\013CallReques" +
      "t\0222\n\010callInfo\030\001 \001(\0132 .com.ukelink.voip.p" +
      "roto.CallInfo\"Z\n\014CallResponse\022:\n\014baseRes" +
      "ponse\030\001 \001(\0132$.com.ukelink.voip.proto.Bas" +
      "eResponse\022\016\n\006callId\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Clientinfo.getDescriptor(),
          Baseresponse.getDescriptor(),
        }, assigner);
    internal_static_com_ukelink_voip_proto_CallInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ukelink_voip_proto_CallInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_voip_proto_CallInfo_descriptor,
        new String[] { "FromUser", "ToUser", "CallMethod", "OriginalId", "IndexId", "CallId", "MessageTime", "Content", });
    internal_static_com_ukelink_voip_proto_CallRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ukelink_voip_proto_CallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_voip_proto_CallRequest_descriptor,
        new String[] { "CallInfo", });
    internal_static_com_ukelink_voip_proto_CallResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ukelink_voip_proto_CallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_voip_proto_CallResponse_descriptor,
        new String[] { "BaseResponse", "CallId", });
    Clientinfo.getDescriptor();
    Baseresponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
