// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userType.proto

package com.ukelink.voip.proto;

public final class UserType {
  private UserType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.ukelink.voip.proto.UserBaseType}
   */
  public enum UserBaseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>error = 0;</code>
     */
    error(0),
    /**
     * <pre>
     *IM
     * </pre>
     *
     * <code>userId = 1;</code>
     */
    userId(1),
    /**
     * <code>sim = 2;</code>
     */
    sim(2),
    /**
     * <code>sip = 3;</code>
     */
    sip(3),
    /**
     * <code>groupId = 4;</code>
     */
    groupId(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>error = 0;</code>
     */
    public static final int error_VALUE = 0;
    /**
     * <pre>
     *IM
     * </pre>
     *
     * <code>userId = 1;</code>
     */
    public static final int userId_VALUE = 1;
    /**
     * <code>sim = 2;</code>
     */
    public static final int sim_VALUE = 2;
    /**
     * <code>sip = 3;</code>
     */
    public static final int sip_VALUE = 3;
    /**
     * <code>groupId = 4;</code>
     */
    public static final int groupId_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static UserBaseType valueOf(int value) {
      return forNumber(value);
    }

    public static UserBaseType forNumber(int value) {
      switch (value) {
        case 0: return error;
        case 1: return userId;
        case 2: return sim;
        case 3: return sip;
        case 4: return groupId;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserBaseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserBaseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserBaseType>() {
            public UserBaseType findValueByNumber(int number) {
              return UserBaseType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ukelink.voip.proto.UserType.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserBaseType[] VALUES = values();

    public static UserBaseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserBaseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ukelink.voip.proto.UserBaseType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016userType.proto\022\026com.ukelink.voip.proto" +
      "*D\n\014UserBaseType\022\t\n\005error\020\000\022\n\n\006userId\020\001\022" +
      "\007\n\003sim\020\002\022\007\n\003sip\020\003\022\013\n\007groupId\020\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
