// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userInfo.proto

package com.ukelink.voip.proto;

public final class UserInfo {
  private UserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserBaseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.voip.proto.UserBaseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     */
    long getUserId();

    /**
     * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
     */
    int getUserTypeValue();
    /**
     * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
     */
    com.ukelink.voip.proto.UserType.UserBaseType getUserType();

    /**
     * <code>string nickName = 3;</code>
     */
    String getNickName();
    /**
     * <code>string nickName = 3;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <code>bytes avatar = 4;</code>
     */
    com.google.protobuf.ByteString getAvatar();

    /**
     * <code>string avatarUrl = 5;</code>
     */
    String getAvatarUrl();
    /**
     * <code>string avatarUrl = 5;</code>
     */
    com.google.protobuf.ByteString
        getAvatarUrlBytes();
  }
  /**
   * Protobuf type {@code com.ukelink.voip.proto.UserBaseInfo}
   */
  public  static final class UserBaseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.voip.proto.UserBaseInfo)
      UserBaseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserBaseInfo.newBuilder() to construct.
    private UserBaseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserBaseInfo() {
      userType_ = 0;
      nickName_ = "";
      avatar_ = com.google.protobuf.ByteString.EMPTY;
      avatarUrl_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserBaseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              userType_ = rawValue;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 34: {

              avatar_ = input.readBytes();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              avatarUrl_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_ukelink_voip_proto_UserBaseInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_ukelink_voip_proto_UserBaseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ukelink.voip.proto.UserInfo.UserBaseInfo.class, com.ukelink.voip.proto.UserInfo.UserBaseInfo.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int USERTYPE_FIELD_NUMBER = 2;
    private int userType_;
    /**
     * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
     */
    public int getUserTypeValue() {
      return userType_;
    }
    /**
     * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
     */
    public com.ukelink.voip.proto.UserType.UserBaseType getUserType() {
      @SuppressWarnings("deprecation")
      com.ukelink.voip.proto.UserType.UserBaseType result = com.ukelink.voip.proto.UserType.UserBaseType.valueOf(userType_);
      return result == null ? com.ukelink.voip.proto.UserType.UserBaseType.UNRECOGNIZED : result;
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private volatile Object nickName_;
    /**
     * <code>string nickName = 3;</code>
     */
    public String getNickName() {
      Object ref = nickName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <code>string nickName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString avatar_;
    /**
     * <code>bytes avatar = 4;</code>
     */
    public com.google.protobuf.ByteString getAvatar() {
      return avatar_;
    }

    public static final int AVATARURL_FIELD_NUMBER = 5;
    private volatile Object avatarUrl_;
    /**
     * <code>string avatarUrl = 5;</code>
     */
    public String getAvatarUrl() {
      Object ref = avatarUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        avatarUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string avatarUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarUrlBytes() {
      Object ref = avatarUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        avatarUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (userType_ != com.ukelink.voip.proto.UserType.UserBaseType.error.getNumber()) {
        output.writeEnum(2, userType_);
      }
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickName_);
      }
      if (!avatar_.isEmpty()) {
        output.writeBytes(4, avatar_);
      }
      if (!getAvatarUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, avatarUrl_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (userType_ != com.ukelink.voip.proto.UserType.UserBaseType.error.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, userType_);
      }
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickName_);
      }
      if (!avatar_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, avatar_);
      }
      if (!getAvatarUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, avatarUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ukelink.voip.proto.UserInfo.UserBaseInfo)) {
        return super.equals(obj);
      }
      com.ukelink.voip.proto.UserInfo.UserBaseInfo other = (com.ukelink.voip.proto.UserInfo.UserBaseInfo) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (userType_ != other.userType_) return false;
      if (!getNickName()
          .equals(other.getNickName())) return false;
      if (!getAvatar()
          .equals(other.getAvatar())) return false;
      if (!getAvatarUrl()
          .equals(other.getAvatarUrl())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + userType_;
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (37 * hash) + AVATARURL_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ukelink.voip.proto.UserInfo.UserBaseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.voip.proto.UserBaseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.voip.proto.UserBaseInfo)
        com.ukelink.voip.proto.UserInfo.UserBaseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_ukelink_voip_proto_UserBaseInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_ukelink_voip_proto_UserBaseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ukelink.voip.proto.UserInfo.UserBaseInfo.class, com.ukelink.voip.proto.UserInfo.UserBaseInfo.Builder.class);
      }

      // Construct using com.ukelink.voip.proto.UserInfo.UserBaseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        userType_ = 0;

        nickName_ = "";

        avatar_ = com.google.protobuf.ByteString.EMPTY;

        avatarUrl_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_ukelink_voip_proto_UserBaseInfo_descriptor;
      }

      @Override
      public com.ukelink.voip.proto.UserInfo.UserBaseInfo getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.ukelink.voip.proto.UserInfo.UserBaseInfo build() {
        com.ukelink.voip.proto.UserInfo.UserBaseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.ukelink.voip.proto.UserInfo.UserBaseInfo buildPartial() {
        com.ukelink.voip.proto.UserInfo.UserBaseInfo result = new com.ukelink.voip.proto.UserInfo.UserBaseInfo(this);
        result.userId_ = userId_;
        result.userType_ = userType_;
        result.nickName_ = nickName_;
        result.avatar_ = avatar_;
        result.avatarUrl_ = avatarUrl_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ukelink.voip.proto.UserInfo.UserBaseInfo) {
          return mergeFrom((com.ukelink.voip.proto.UserInfo.UserBaseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ukelink.voip.proto.UserInfo.UserBaseInfo other) {
        if (other == getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.userType_ != 0) {
          setUserTypeValue(other.getUserTypeValue());
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.getAvatar() != com.google.protobuf.ByteString.EMPTY) {
          setAvatar(other.getAvatar());
        }
        if (!other.getAvatarUrl().isEmpty()) {
          avatarUrl_ = other.avatarUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ukelink.voip.proto.UserInfo.UserBaseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ukelink.voip.proto.UserInfo.UserBaseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private int userType_ = 0;
      /**
       * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
       */
      public int getUserTypeValue() {
        return userType_;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
       */
      public Builder setUserTypeValue(int value) {
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
       */
      public com.ukelink.voip.proto.UserType.UserBaseType getUserType() {
        @SuppressWarnings("deprecation")
        com.ukelink.voip.proto.UserType.UserBaseType result = com.ukelink.voip.proto.UserType.UserBaseType.valueOf(userType_);
        return result == null ? com.ukelink.voip.proto.UserType.UserBaseType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
       */
      public Builder setUserType(com.ukelink.voip.proto.UserType.UserBaseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        userType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseType userType = 2;</code>
       */
      public Builder clearUserType() {
        
        userType_ = 0;
        onChanged();
        return this;
      }

      private Object nickName_ = "";
      /**
       * <code>string nickName = 3;</code>
       */
      public String getNickName() {
        Object ref = nickName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder setNickName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString avatar_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes avatar = 4;</code>
       */
      public com.google.protobuf.ByteString getAvatar() {
        return avatar_;
      }
      /**
       * <code>bytes avatar = 4;</code>
       */
      public Builder setAvatar(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes avatar = 4;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }

      private Object avatarUrl_ = "";
      /**
       * <code>string avatarUrl = 5;</code>
       */
      public String getAvatarUrl() {
        Object ref = avatarUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          avatarUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string avatarUrl = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarUrlBytes() {
        Object ref = avatarUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          avatarUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avatarUrl = 5;</code>
       */
      public Builder setAvatarUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatarUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string avatarUrl = 5;</code>
       */
      public Builder clearAvatarUrl() {
        
        avatarUrl_ = getDefaultInstance().getAvatarUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string avatarUrl = 5;</code>
       */
      public Builder setAvatarUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatarUrl_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.voip.proto.UserBaseInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.voip.proto.UserBaseInfo)
    private static final com.ukelink.voip.proto.UserInfo.UserBaseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ukelink.voip.proto.UserInfo.UserBaseInfo();
    }

    public static com.ukelink.voip.proto.UserInfo.UserBaseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserBaseInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserBaseInfo>() {
      @Override
      public UserBaseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserBaseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserBaseInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserBaseInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public com.ukelink.voip.proto.UserInfo.UserBaseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserDetailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ukelink.voip.proto.UserDetailInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
     */
    boolean hasUserBaseInfo();
    /**
     * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
     */
    com.ukelink.voip.proto.UserInfo.UserBaseInfo getUserBaseInfo();
    /**
     * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
     */
    com.ukelink.voip.proto.UserInfo.UserBaseInfoOrBuilder getUserBaseInfoOrBuilder();

    /**
     * <code>string gender = 2;</code>
     */
    String getGender();
    /**
     * <code>string gender = 2;</code>
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>string address = 3;</code>
     */
    String getAddress();
    /**
     * <code>string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string phoneNumber = 4;</code>
     */
    String getPhoneNumber();
    /**
     * <code>string phoneNumber = 4;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();

    /**
     * <code>string wechat = 5;</code>
     */
    String getWechat();
    /**
     * <code>string wechat = 5;</code>
     */
    com.google.protobuf.ByteString
        getWechatBytes();

    /**
     * <code>string weibo = 6;</code>
     */
    String getWeibo();
    /**
     * <code>string weibo = 6;</code>
     */
    com.google.protobuf.ByteString
        getWeiboBytes();

    /**
     * <code>string mail = 7;</code>
     */
    String getMail();
    /**
     * <code>string mail = 7;</code>
     */
    com.google.protobuf.ByteString
        getMailBytes();

    /**
     * <code>string signature = 8;</code>
     */
    String getSignature();
    /**
     * <code>string signature = 8;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>string area = 9;</code>
     */
    String getArea();
    /**
     * <code>string area = 9;</code>
     */
    com.google.protobuf.ByteString
        getAreaBytes();
  }
  /**
   * Protobuf type {@code com.ukelink.voip.proto.UserDetailInfo}
   */
  public  static final class UserDetailInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ukelink.voip.proto.UserDetailInfo)
      UserDetailInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserDetailInfo.newBuilder() to construct.
    private UserDetailInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserDetailInfo() {
      gender_ = "";
      address_ = "";
      phoneNumber_ = "";
      wechat_ = "";
      weibo_ = "";
      mail_ = "";
      signature_ = "";
      area_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserDetailInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.ukelink.voip.proto.UserInfo.UserBaseInfo.Builder subBuilder = null;
              if (userBaseInfo_ != null) {
                subBuilder = userBaseInfo_.toBuilder();
              }
              userBaseInfo_ = input.readMessage(com.ukelink.voip.proto.UserInfo.UserBaseInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userBaseInfo_);
                userBaseInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              gender_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              phoneNumber_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              wechat_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              weibo_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              mail_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              signature_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              area_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_ukelink_voip_proto_UserDetailInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_ukelink_voip_proto_UserDetailInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ukelink.voip.proto.UserInfo.UserDetailInfo.class, com.ukelink.voip.proto.UserInfo.UserDetailInfo.Builder.class);
    }

    public static final int USERBASEINFO_FIELD_NUMBER = 1;
    private com.ukelink.voip.proto.UserInfo.UserBaseInfo userBaseInfo_;
    /**
     * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
     */
    public boolean hasUserBaseInfo() {
      return userBaseInfo_ != null;
    }
    /**
     * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
     */
    public com.ukelink.voip.proto.UserInfo.UserBaseInfo getUserBaseInfo() {
      return userBaseInfo_ == null ? com.ukelink.voip.proto.UserInfo.UserBaseInfo.getDefaultInstance() : userBaseInfo_;
    }
    /**
     * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
     */
    public com.ukelink.voip.proto.UserInfo.UserBaseInfoOrBuilder getUserBaseInfoOrBuilder() {
      return getUserBaseInfo();
    }

    public static final int GENDER_FIELD_NUMBER = 2;
    private volatile Object gender_;
    /**
     * <code>string gender = 2;</code>
     */
    public String getGender() {
      Object ref = gender_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <code>string gender = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile Object address_;
    /**
     * <code>string address = 3;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 4;
    private volatile Object phoneNumber_;
    /**
     * <code>string phoneNumber = 4;</code>
     */
    public String getPhoneNumber() {
      Object ref = phoneNumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string phoneNumber = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      Object ref = phoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WECHAT_FIELD_NUMBER = 5;
    private volatile Object wechat_;
    /**
     * <code>string wechat = 5;</code>
     */
    public String getWechat() {
      Object ref = wechat_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        wechat_ = s;
        return s;
      }
    }
    /**
     * <code>string wechat = 5;</code>
     */
    public com.google.protobuf.ByteString
        getWechatBytes() {
      Object ref = wechat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        wechat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEIBO_FIELD_NUMBER = 6;
    private volatile Object weibo_;
    /**
     * <code>string weibo = 6;</code>
     */
    public String getWeibo() {
      Object ref = weibo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        weibo_ = s;
        return s;
      }
    }
    /**
     * <code>string weibo = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWeiboBytes() {
      Object ref = weibo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        weibo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAIL_FIELD_NUMBER = 7;
    private volatile Object mail_;
    /**
     * <code>string mail = 7;</code>
     */
    public String getMail() {
      Object ref = mail_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mail_ = s;
        return s;
      }
    }
    /**
     * <code>string mail = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMailBytes() {
      Object ref = mail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 8;
    private volatile Object signature_;
    /**
     * <code>string signature = 8;</code>
     */
    public String getSignature() {
      Object ref = signature_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <code>string signature = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AREA_FIELD_NUMBER = 9;
    private volatile Object area_;
    /**
     * <code>string area = 9;</code>
     */
    public String getArea() {
      Object ref = area_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        area_ = s;
        return s;
      }
    }
    /**
     * <code>string area = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAreaBytes() {
      Object ref = area_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        area_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userBaseInfo_ != null) {
        output.writeMessage(1, getUserBaseInfo());
      }
      if (!getGenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gender_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phoneNumber_);
      }
      if (!getWechatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, wechat_);
      }
      if (!getWeiboBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, weibo_);
      }
      if (!getMailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, mail_);
      }
      if (!getSignatureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, signature_);
      }
      if (!getAreaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, area_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userBaseInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserBaseInfo());
      }
      if (!getGenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gender_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phoneNumber_);
      }
      if (!getWechatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, wechat_);
      }
      if (!getWeiboBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, weibo_);
      }
      if (!getMailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, mail_);
      }
      if (!getSignatureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, signature_);
      }
      if (!getAreaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, area_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ukelink.voip.proto.UserInfo.UserDetailInfo)) {
        return super.equals(obj);
      }
      com.ukelink.voip.proto.UserInfo.UserDetailInfo other = (com.ukelink.voip.proto.UserInfo.UserDetailInfo) obj;

      if (hasUserBaseInfo() != other.hasUserBaseInfo()) return false;
      if (hasUserBaseInfo()) {
        if (!getUserBaseInfo()
            .equals(other.getUserBaseInfo())) return false;
      }
      if (!getGender()
          .equals(other.getGender())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getPhoneNumber()
          .equals(other.getPhoneNumber())) return false;
      if (!getWechat()
          .equals(other.getWechat())) return false;
      if (!getWeibo()
          .equals(other.getWeibo())) return false;
      if (!getMail()
          .equals(other.getMail())) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!getArea()
          .equals(other.getArea())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserBaseInfo()) {
        hash = (37 * hash) + USERBASEINFO_FIELD_NUMBER;
        hash = (53 * hash) + getUserBaseInfo().hashCode();
      }
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      hash = (37 * hash) + WECHAT_FIELD_NUMBER;
      hash = (53 * hash) + getWechat().hashCode();
      hash = (37 * hash) + WEIBO_FIELD_NUMBER;
      hash = (53 * hash) + getWeibo().hashCode();
      hash = (37 * hash) + MAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMail().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + AREA_FIELD_NUMBER;
      hash = (53 * hash) + getArea().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ukelink.voip.proto.UserInfo.UserDetailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ukelink.voip.proto.UserDetailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ukelink.voip.proto.UserDetailInfo)
        com.ukelink.voip.proto.UserInfo.UserDetailInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_ukelink_voip_proto_UserDetailInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_ukelink_voip_proto_UserDetailInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ukelink.voip.proto.UserInfo.UserDetailInfo.class, com.ukelink.voip.proto.UserInfo.UserDetailInfo.Builder.class);
      }

      // Construct using com.ukelink.voip.proto.UserInfo.UserDetailInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (userBaseInfoBuilder_ == null) {
          userBaseInfo_ = null;
        } else {
          userBaseInfo_ = null;
          userBaseInfoBuilder_ = null;
        }
        gender_ = "";

        address_ = "";

        phoneNumber_ = "";

        wechat_ = "";

        weibo_ = "";

        mail_ = "";

        signature_ = "";

        area_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_ukelink_voip_proto_UserDetailInfo_descriptor;
      }

      @Override
      public com.ukelink.voip.proto.UserInfo.UserDetailInfo getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.ukelink.voip.proto.UserInfo.UserDetailInfo build() {
        com.ukelink.voip.proto.UserInfo.UserDetailInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.ukelink.voip.proto.UserInfo.UserDetailInfo buildPartial() {
        com.ukelink.voip.proto.UserInfo.UserDetailInfo result = new com.ukelink.voip.proto.UserInfo.UserDetailInfo(this);
        if (userBaseInfoBuilder_ == null) {
          result.userBaseInfo_ = userBaseInfo_;
        } else {
          result.userBaseInfo_ = userBaseInfoBuilder_.build();
        }
        result.gender_ = gender_;
        result.address_ = address_;
        result.phoneNumber_ = phoneNumber_;
        result.wechat_ = wechat_;
        result.weibo_ = weibo_;
        result.mail_ = mail_;
        result.signature_ = signature_;
        result.area_ = area_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ukelink.voip.proto.UserInfo.UserDetailInfo) {
          return mergeFrom((com.ukelink.voip.proto.UserInfo.UserDetailInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ukelink.voip.proto.UserInfo.UserDetailInfo other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasUserBaseInfo()) {
          mergeUserBaseInfo(other.getUserBaseInfo());
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        if (!other.getWechat().isEmpty()) {
          wechat_ = other.wechat_;
          onChanged();
        }
        if (!other.getWeibo().isEmpty()) {
          weibo_ = other.weibo_;
          onChanged();
        }
        if (!other.getMail().isEmpty()) {
          mail_ = other.mail_;
          onChanged();
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          onChanged();
        }
        if (!other.getArea().isEmpty()) {
          area_ = other.area_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ukelink.voip.proto.UserInfo.UserDetailInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ukelink.voip.proto.UserInfo.UserDetailInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.ukelink.voip.proto.UserInfo.UserBaseInfo userBaseInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ukelink.voip.proto.UserInfo.UserBaseInfo, com.ukelink.voip.proto.UserInfo.UserBaseInfo.Builder, com.ukelink.voip.proto.UserInfo.UserBaseInfoOrBuilder> userBaseInfoBuilder_;
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      public boolean hasUserBaseInfo() {
        return userBaseInfoBuilder_ != null || userBaseInfo_ != null;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      public com.ukelink.voip.proto.UserInfo.UserBaseInfo getUserBaseInfo() {
        if (userBaseInfoBuilder_ == null) {
          return userBaseInfo_ == null ? com.ukelink.voip.proto.UserInfo.UserBaseInfo.getDefaultInstance() : userBaseInfo_;
        } else {
          return userBaseInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      public Builder setUserBaseInfo(com.ukelink.voip.proto.UserInfo.UserBaseInfo value) {
        if (userBaseInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userBaseInfo_ = value;
          onChanged();
        } else {
          userBaseInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      public Builder setUserBaseInfo(
          com.ukelink.voip.proto.UserInfo.UserBaseInfo.Builder builderForValue) {
        if (userBaseInfoBuilder_ == null) {
          userBaseInfo_ = builderForValue.build();
          onChanged();
        } else {
          userBaseInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      public Builder mergeUserBaseInfo(com.ukelink.voip.proto.UserInfo.UserBaseInfo value) {
        if (userBaseInfoBuilder_ == null) {
          if (userBaseInfo_ != null) {
            userBaseInfo_ =
              com.ukelink.voip.proto.UserInfo.UserBaseInfo.newBuilder(userBaseInfo_).mergeFrom(value).buildPartial();
          } else {
            userBaseInfo_ = value;
          }
          onChanged();
        } else {
          userBaseInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      public Builder clearUserBaseInfo() {
        if (userBaseInfoBuilder_ == null) {
          userBaseInfo_ = null;
          onChanged();
        } else {
          userBaseInfo_ = null;
          userBaseInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      public com.ukelink.voip.proto.UserInfo.UserBaseInfo.Builder getUserBaseInfoBuilder() {
        
        onChanged();
        return getUserBaseInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      public com.ukelink.voip.proto.UserInfo.UserBaseInfoOrBuilder getUserBaseInfoOrBuilder() {
        if (userBaseInfoBuilder_ != null) {
          return userBaseInfoBuilder_.getMessageOrBuilder();
        } else {
          return userBaseInfo_ == null ?
              com.ukelink.voip.proto.UserInfo.UserBaseInfo.getDefaultInstance() : userBaseInfo_;
        }
      }
      /**
       * <code>.com.ukelink.voip.proto.UserBaseInfo userBaseInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ukelink.voip.proto.UserInfo.UserBaseInfo, com.ukelink.voip.proto.UserInfo.UserBaseInfo.Builder, com.ukelink.voip.proto.UserInfo.UserBaseInfoOrBuilder> 
          getUserBaseInfoFieldBuilder() {
        if (userBaseInfoBuilder_ == null) {
          userBaseInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ukelink.voip.proto.UserInfo.UserBaseInfo, com.ukelink.voip.proto.UserInfo.UserBaseInfo.Builder, com.ukelink.voip.proto.UserInfo.UserBaseInfoOrBuilder>(
                  getUserBaseInfo(),
                  getParentForChildren(),
                  isClean());
          userBaseInfo_ = null;
        }
        return userBaseInfoBuilder_;
      }

      private Object gender_ = "";
      /**
       * <code>string gender = 2;</code>
       */
      public String getGender() {
        Object ref = gender_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string gender = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gender = 2;</code>
       */
      public Builder setGender(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 2;</code>
       */
      public Builder clearGender() {
        
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 2;</code>
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gender_ = value;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>string address = 3;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private Object phoneNumber_ = "";
      /**
       * <code>string phoneNumber = 4;</code>
       */
      public String getPhoneNumber() {
        Object ref = phoneNumber_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string phoneNumber = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phoneNumber = 4;</code>
       */
      public Builder setPhoneNumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNumber = 4;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNumber = 4;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }

      private Object wechat_ = "";
      /**
       * <code>string wechat = 5;</code>
       */
      public String getWechat() {
        Object ref = wechat_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          wechat_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string wechat = 5;</code>
       */
      public com.google.protobuf.ByteString
          getWechatBytes() {
        Object ref = wechat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          wechat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string wechat = 5;</code>
       */
      public Builder setWechat(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wechat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string wechat = 5;</code>
       */
      public Builder clearWechat() {
        
        wechat_ = getDefaultInstance().getWechat();
        onChanged();
        return this;
      }
      /**
       * <code>string wechat = 5;</code>
       */
      public Builder setWechatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wechat_ = value;
        onChanged();
        return this;
      }

      private Object weibo_ = "";
      /**
       * <code>string weibo = 6;</code>
       */
      public String getWeibo() {
        Object ref = weibo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          weibo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string weibo = 6;</code>
       */
      public com.google.protobuf.ByteString
          getWeiboBytes() {
        Object ref = weibo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          weibo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string weibo = 6;</code>
       */
      public Builder setWeibo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weibo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string weibo = 6;</code>
       */
      public Builder clearWeibo() {
        
        weibo_ = getDefaultInstance().getWeibo();
        onChanged();
        return this;
      }
      /**
       * <code>string weibo = 6;</code>
       */
      public Builder setWeiboBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weibo_ = value;
        onChanged();
        return this;
      }

      private Object mail_ = "";
      /**
       * <code>string mail = 7;</code>
       */
      public String getMail() {
        Object ref = mail_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mail_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mail = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMailBytes() {
        Object ref = mail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mail = 7;</code>
       */
      public Builder setMail(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 7;</code>
       */
      public Builder clearMail() {
        
        mail_ = getDefaultInstance().getMail();
        onChanged();
        return this;
      }
      /**
       * <code>string mail = 7;</code>
       */
      public Builder setMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mail_ = value;
        onChanged();
        return this;
      }

      private Object signature_ = "";
      /**
       * <code>string signature = 8;</code>
       */
      public String getSignature() {
        Object ref = signature_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string signature = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signature = 8;</code>
       */
      public Builder setSignature(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 8;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 8;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signature_ = value;
        onChanged();
        return this;
      }

      private Object area_ = "";
      /**
       * <code>string area = 9;</code>
       */
      public String getArea() {
        Object ref = area_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          area_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string area = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAreaBytes() {
        Object ref = area_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          area_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string area = 9;</code>
       */
      public Builder setArea(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        area_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string area = 9;</code>
       */
      public Builder clearArea() {
        
        area_ = getDefaultInstance().getArea();
        onChanged();
        return this;
      }
      /**
       * <code>string area = 9;</code>
       */
      public Builder setAreaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        area_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ukelink.voip.proto.UserDetailInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ukelink.voip.proto.UserDetailInfo)
    private static final com.ukelink.voip.proto.UserInfo.UserDetailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ukelink.voip.proto.UserInfo.UserDetailInfo();
    }

    public static com.ukelink.voip.proto.UserInfo.UserDetailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserDetailInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserDetailInfo>() {
      @Override
      public UserDetailInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserDetailInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserDetailInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserDetailInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public com.ukelink.voip.proto.UserInfo.UserDetailInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_voip_proto_UserBaseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_voip_proto_UserBaseInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ukelink_voip_proto_UserDetailInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ukelink_voip_proto_UserDetailInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016userInfo.proto\022\026com.ukelink.voip.proto" +
      "\032\016userType.proto\"\213\001\n\014UserBaseInfo\022\016\n\006use" +
      "rId\030\001 \001(\003\0226\n\010userType\030\002 \001(\0162$.com.ukelin" +
      "k.voip.proto.UserBaseType\022\020\n\010nickName\030\003 " +
      "\001(\t\022\016\n\006avatar\030\004 \001(\014\022\021\n\tavatarUrl\030\005 \001(\t\"\320" +
      "\001\n\016UserDetailInfo\022:\n\014userBaseInfo\030\001 \001(\0132" +
      "$.com.ukelink.voip.proto.UserBaseInfo\022\016\n" +
      "\006gender\030\002 \001(\t\022\017\n\007address\030\003 \001(\t\022\023\n\013phoneN" +
      "umber\030\004 \001(\t\022\016\n\006wechat\030\005 \001(\t\022\r\n\005weibo\030\006 \001" +
      "(\t\022\014\n\004mail\030\007 \001(\t\022\021\n\tsignature\030\010 \001(\t\022\014\n\004a" +
      "rea\030\t \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ukelink.voip.proto.UserType.getDescriptor(),
        }, assigner);
    internal_static_com_ukelink_voip_proto_UserBaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ukelink_voip_proto_UserBaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_voip_proto_UserBaseInfo_descriptor,
        new String[] { "UserId", "UserType", "NickName", "Avatar", "AvatarUrl", });
    internal_static_com_ukelink_voip_proto_UserDetailInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ukelink_voip_proto_UserDetailInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ukelink_voip_proto_UserDetailInfo_descriptor,
        new String[] { "UserBaseInfo", "Gender", "Address", "PhoneNumber", "Wechat", "Weibo", "Mail", "Signature", "Area", });
    com.ukelink.voip.proto.UserType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
